### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DJZeroAction** [dariolupo/dark-mellow_bitwig#2]
Bitwig meets themes... Let's go!
Applying theme from: /home/user/Downloads/bitwig themes/Dark_Mellow_1.1/Dark Mellow 1.1/dark_mellow.json
Exception in thread "main" java.lang.NullPointerException: Cannot read field "instructions" because "this.methodNode" is null
        at dev.berikai.BitwigTheme.core.ThemeClass.setTheme(ThemeClass.java:124)
        at dev.berikai.BitwigTheme.Main.applyTheme(Main.java:87)
        at dev.berikai.BitwigTheme.Main.main(Main.java:57)

**Comment by djraw** [comment]
Could you issue this command `java —version`

Make sure you have java 17 or greater.
